CodingClient/Models/ApiHelper.cs
using System;
using System.Threading.Tasks;
using RestSharp;

namespace CodingClient.Models
{
  public class ApiHelper
  {
    public static async Task<string> Get(string resource, string id)
    {
      RestClient client = new("http://localhost:5000/api");
      RestRequest request = new($"{resource}/{id}", Method.GET);
      var response = await client.ExecuteTaskAsync(request);
      return response.Content;
    }

    public static async Task Post(string newPost, string resource, string id)
    {
      Console.WriteLine("\n\nHIT CLIENT APIHELPER method POST: {0} {1} {2}", newPost, resource, id);
      RestClient client = new("http://localhost:5000/api");
      RestRequest request = new($"{resource}/{id}/", Method.POST);
      request.AddHeader("Content-Type", "application/json");
      request.AddJsonBody(newPost);
      Console.WriteLine("REQUEST: {0}", request.ToString());
      var response = await client.ExecuteTaskAsync(request);
    }

    public static async Task Put(string newPost, string resource, string id)
    {
      RestClient client = new("http://localhost:5000/api");
      RestRequest request = new($"{resource}/{id}", Method.PUT);
      request.AddHeader("Content-Type", "application/json");
      request.AddJsonBody(newPost);
      var response = await client.ExecuteTaskAsync(request);
    }

    public static async Task<string> Delete(string resource, string id)
    {
      RestClient client = new("http://localhost:5000/api");
      RestRequest request = new($"{resource}/{id}", Method.DELETE);
      request.AddHeader("Content-Type", "application/json");
      var response = await client.ExecuteTaskAsync(request);
      return response.Content;
    }
  }
}

CodingClient/Models/Board.cs
using Newtonsoft;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System;

namespace CodingClient.Models
{
  public class Board
  {
    public string BoardId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public virtual ICollection<Post> Posts { get; set; }
    public static List<Board> Get(string resource, string id)
    {
      var apiCallTask = ApiHelper.Get(resource, id);
      var result = apiCallTask.Result;

      JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
      List<Board> boardList = JsonConvert.DeserializeObject<List<Board>>(jsonResponse.ToString());

      return boardList;
    }
  }
}

CodingClient/Models/Post.cs
using System.Collections.Generic;
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CodingClient.Models
{
  public class Post
  {
    public string PostId { get; set; }
    public string Body { get; set; }
    public virtual ICollection<Reply> Replies { get; set; }
    public string BoardUserId { get; set; }
    public string BoardId { get; set; }
    public int VoteCount { get; set; }
    public static List<Post> Get(string resource, string id)
    {
      var apiCallTask = ApiHelper.Get(resource, id);
      var result = apiCallTask.Result;

      JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
      List<Post> postList = JsonConvert.DeserializeObject<List<Post>>(jsonResponse.ToString());

      return postList;
    }

    public static void Create(Post post, string boardId)
    {
      Console.WriteLine("HIT POST MODEL CREATE METHOD {0} {1} {2}", post.Body, post.BoardUserId, boardId);
      string jsonPost = JsonConvert.SerializeObject(post);
      Console.WriteLine("AFTER JSONPOST {0}", jsonPost);
      var apiCallTask = ApiHelper.Post(jsonPost, "posts", boardId);
    }

    // public static void Put(Post post)
    // {
    //   string jsonPost = JsonConvert.SerializeObject(post);
    //   var apiCallTask = ApiHelper.Put(post.PostId, jsonPost);
    // }

    // public static void Delete(string resource, string id)
    // {
    //   var apiCallTask = ApiHelper.Delete(resource, id);
    // }
  }
}

CodingClient/Models/Reply.cs
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CodingClient.Models
{
  public class Reply
  {
    // public Reply()
    // {
    //   ReplyId = Guid.NewGuid().ToString();
    //   VoteCount = 0;
    // }
    public string ReplyId { get; set; }
    public string Body { get; set; }
    public string BoardUserId { get; set; }
    public string PostId { get; set; }
    public int VoteCount { get; set; }

    // public static List<Reply> Get(string resource, string id)
    // {
    //   var apiCallTask = ApiHelper.Get(resource, id);
    //   var result = apiCallTask.Result;

    //   JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
    //   List<Reply> replyList = JsonConvert.DeserializeObject<List<Reply>>(jsonResponse.ToString());

    //   return replyList;
    // }

    // public static void Post(Reply reply)
    // {
    //   string jsonReply = JsonConvert.SerializeObject(reply);
    //   var apiCallTask = ApiHelper.Post(jsonReply);
    // }

    // public static void Put(Reply reply)
    // {
    //   string jsonReply = JsonConvert.SerializeObject(reply);
    //   var apiCallTask = ApiHelper.Put(reply.ReplyId, jsonReply);
    // }

    // public static void Delete(string resource, string id)
    // {
    //   var apiCallTask = ApiHelper.Delete(resource, id);
    // }
  }
}

CodingClient/Controllers/BoardsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CodingClient.Models;

namespace CodingClient.Controllers
{
  public class BoardsController : Controller
  {
    [HttpGet("/boards/all")]
    public IActionResult Index()
    {
      var theBoard = Board.Get("boards", "all");
      return View(theBoard);
    }

    [HttpGet("/boards/{boardId}")]
    public IActionResult Details(string boardId)
    {
      var theBoard = Board.Get("boards", boardId);
      return View(theBoard);
    }
  }
}

CodingClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CodingClient.Models;

namespace CodingClient.Controllers
{
  public class HomeController : Controller
  {
    public IActionResult Index()
    {
      return View();
    }
  }
}

CodingClient/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CodingClient.Models;

namespace CodingClient.Controllers
{
  public class PostsController : Controller
  {
    [HttpGet("/posts/all")]
    public IActionResult Index()
    {
      var thePost = Post.Get("posts", "all");
      return View(thePost);
    }

    [HttpGet("/posts/{postId}")]
    public IActionResult Details(string postId)
    {
      var thePost = Post.Get("posts", postId);
      return View(thePost);
    }

    [HttpPost("/posts/create")]
    public IActionResult Create(Post newPost)
    {
      Console.WriteLine("\n\nHIT POST CREATE ROUTE. {0}", newPost);
      Console.WriteLine(newPost.Body);
      Post.Create(newPost, newPost.BoardId);
      return RedirectToAction("Index");
    }
  }
}

CodingClient/Controllers/RepliesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CodingClient.Models;

namespace CodingClient.Controllers
{
  public class RepliesController : Controller
  {

  }
}

CodingClient/Views/Boards/Details.cshtml
@model List<CodingClient.Models.Board>;

<div class="container-fluid">
  <h1>Boards - @Model[0].Name</h1>

  <div class="container">
    <h3>@Model[0].Name</h3>
    <p>@Model[0].Description</p>
    <div class="container">
      @if (@Model[0].Posts.Count == 0)
      {
        <p>No Posts!</p>
      }
      else
      {
        @foreach (Post p in Model[0].Posts)
        {
          <div class="card">
            @Html.ActionLink(@p.Body, @p.PostId, "posts")
          </div>
        }
      }
    </div>
    <div class="container">
      <form action="/posts/create" method="post">
        <div class="form-group">
          <label for="body">Content</label>
          <input type="text" name="body" id="body" placeholder="type here..." required="required" />
          <input type="hidden" name="VoteCount" value=1 />
          <input type="hidden" name="BoardUserId" value="One" />
          <input type="hidden" name="BoardId" value="@Model[0].BoardId" />
          <button class="btn btn-block btn-primary" type="submit">New Post</button>
        </div>
      </form>
    </div>
  </div>
</div>

CodingClient/Views/Boards/Index.cshtml
@model List<CodingClient.Models.Board>;

<div class="container-fluid">
  <h1>Boards - All</h1>

  <div class="container">
    @foreach (Board b in Model)
    {
      <h3>@Html.ActionLink(@b.Name, b.BoardId, "boards")</h3>

      <p>@b.Description</p>
    }
  </div>
</div>

CodingClient/Views/Home/Index.cshtml
@{
  ViewData["Title"] = "Coding Board - Home";
}

<div class="text-center">
  <h1 class="display-4">The Coding Board!</h1>
  <a href="/boards">View all boards</a>
</div>

CodingClient/Views/Posts/Index.cshtml
@model CodingClient.Models.Post;

<div class="container">
  <h1>Posts - </h1>

</div>

CodingClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - CodingClient</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
  <header>
      <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
          <div class="container">
              <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodingClient</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                      aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                  <ul class="navbar-nav flex-grow-1">
                      <li class="nav-item">
                          <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link text-dark" asp-area="" asp-controller="Boards" asp-action="Index">Boards</a>
                      </li>
                  </ul>
              </div>
          </div>
      </nav>
  </header>
  <div class="container">
      <main role="main" class="pb-3">
          @RenderBody()
      </main>
  </div>

  <footer class="border-top footer text-muted">
      <div class="container">
          &copy; 2021 - CodingClient
      </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>